################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 3 - Alpha",
		"License :: OSI Approved :: Apache Software License",
		"Programming Language :: Python :: 3",
	],
	description = "This python module is part of the Thaniya server. It provides a way to run scripts via sudo in a controlled way.",
	include_package_data = False,
	install_requires = [
	],
	keywords = [
		"sudo",
		"thaniya",
	],
	license = "Apache2",
	name = "thaniya_server_sudo",
	packages = [
		"thaniya_server_sudo",
	],
	version = "0.2021.1.18",
	zip_safe = False,
	long_description = readme(),
	long_description_content_type="text/markdown",
)
