################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 4 - Beta",
		"License :: OSI Approved :: Apache Software License",
		"Programming Language :: Python :: 3",
	],
	description = "This python module implements the Thania Backup Client.",
	include_package_data = False,
	install_requires = [
		"jk_utils",
		"jk_mediawiki",
		"jk_typo3",
		"jk_json",
		"jk_logging",
		"jk_mounting",
		"jk_simpleexec",
		"jk_typing",
		"jk_pwdinput",
		"shutils",
	],
	keywords = [
		"backup",
	],
	license = "Apache2",
	name = "thaniya_client",
	packages = [
		"thaniya_client",
		"thaniya_client.utils",
		"thaniya_client.tools",
		"thaniya_client.tasks",
		"thaniya_client.cfg",
		"thaniya_client.server",
	],
	scripts = [
		"bin/thania_helper_mysql_get_db_size.py",
	],
	version = "0.2020.12.7",
	zip_safe = False,
	long_description = readme(),
	long_description_content_type="text/markdown",
)
